In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[4]

np.int64(4)

In [7]:
arr[3:7]

array([3, 4, 5, 6])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [12]:
#broad cast
arr[0:4] = 100

In [13]:
arr = np.arange(0,11)

In [14]:
slice = arr[0:5]

In [15]:
slice[:] = 10

In [16]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [17]:
# even if a sliced of an array is taken and that slice was mutated (changed) it'll affect the original array

In [18]:
# for copy
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100

In [20]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
# indexing matrices
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# double bracket notation
arr2d[0][0]

np.int64(5)

In [25]:
# single bracket notation
arr2d[2,1]

np.int64(40)

In [26]:
# sub matrices of the original
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
arr2d[1:,:1]

array([[20],
       [35]])

In [28]:
arr2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [29]:
arr2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [30]:
# conditional selections
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [33]:
arr2d = np.arange(50).reshape(5,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
arr2d[arr2d % 5 == 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
arr2d[2:,5:]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [36]:
arr2d[arr2d[2:,5:]]

IndexError: index 25 is out of bounds for axis 0 with size 5

In [37]:
arr2d[arr2d % 5 == 0].reshape(5,2)

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [38]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])