## NumPy Arrays

In [4]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# similar to range function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# randoms
np.random.rand(5)

array([0.13254483, 0.75022839, 0.59327417, 0.09220135, 0.89921476])

In [22]:
np.random.rand(5,3)

array([[0.08788248, 0.02219189, 0.87680622],
       [0.7684129 , 0.06420648, 0.19880329],
       [0.20403684, 0.74965484, 0.74510829],
       [0.44570696, 0.12637265, 0.93883714],
       [0.25442738, 0.60591677, 0.08545927]])

In [23]:
np.random.randn(2)

array([-0.65772508, -0.94760663])

In [24]:
np.random.randn(2,4)

array([[ 0.73334373,  0.85775068, -0.29328761,  0.02488442],
       [ 0.44148666,  0.74904385, -0.04531879, -0.19149339]])

In [26]:
np.random.randint(5,8)

7

In [27]:
np.random.randint(5,8,1)

array([7])

In [29]:
np.random.randint(5,10,3)

array([5, 6, 5])

In [30]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# reshape
arr.reshape(5,5)
# this works only if the size of the matrix is equal to the number of element in the original matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = np.random.randint(0,100,20)
ranarr

array([17, 51, 21, 50, 15, 35, 36, 59, 97,  2, 10, 17, 21, 46, 47, 53, 15,
       94, 38, 49])

In [34]:
ranarr.max()

np.int64(97)

In [35]:
ranarr.min()

np.int64(2)

In [36]:
ranarr.argmax()

np.int64(8)

In [37]:
ranarr.argmin()

np.int64(9)

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5).shape

(5, 5)

In [41]:
arr.dtype

dtype('int64')